<?php
declare(strict_types=1);
/**
 * This file is part of stubbles.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace stubbles\values;
use InvalidArgumentException;
/**
 * Represents the root path within a project.
 *
 * The root path is defined as the path in which the whole application resides.
 * In case the application is inside a phar, it's the directory where the phar
 * is stored.
 *
 * @since 4.0.0
 * @Singleton
 */
class Rootpath
{
    /**
     * returns default rootpath
     *
     * Especially suited where rootpath is expected as string but a cast of a
     * newly created instance looks ugly.
     *
     * @since 8.1.0
     */
    public static function default(): string
    {
        static $default;
        if (null === $default) {
            $default = new self();
        }

        return $default->__toString();
    }

    private string $rootpath;

    /**
     * constructor
     *
     * If no root path is given it tries to detect it automatically. Detection
     * works the following way:
     * - In case the application is inside a phar, it's the directory where the
     *   phar is stored.
     * - Try to locate the vendor/autoload.php file generated by Composer, and
     *   go up one above to vendor/..
     *
     * @throws InvalidArgumentException in case a root path is given but does not exist
     */
    public function __construct(?string $rootpath = null)
    {
        if (null !== $rootpath && !file_exists($rootpath)) {
            throw new InvalidArgumentException(
                'Given rootpath "' . $rootpath . '" does not exist'
            );
        }

        // prevent errors when using vfsStream URIs in unit tests.
        if (null !== $rootpath && substr($rootpath, 0, 6) === 'vfs://') {
            $this->rootpath = $rootpath;
        } elseif (null !== $rootpath) {
            $r = realpath($rootpath);
            if (false === $r) {
                throw new InvalidArgumentException('Can not resolve given rootpath');
            }

            $this->rootpath = $r;
        } else {
          $this->rootpath = $this->detectRootPath();
        }
    }

    /**
     * casts given value to an instance of Rootpath
     */
    public static function castFrom(string|self|null $rootpath): self
    {
        if ($rootpath instanceof self) {
            return $rootpath;
        }

        return new self($rootpath);
    }

    /**
     * returns root path
     */
    public function __toString(): string
    {
        return $this->rootpath;
    }

    /**
     * returns absolute path to given local path
     *
     * Supports arbitrary lists of arguments, e.g.
     * <code>$rootpath->to('src', 'main', 'php', 'Example.php')</code>
     * will return "path/to/root/src/main/php/Example.php".
     */
    public function to(string ...$pathParts): string
    {
        return $this->rootpath . DIRECTORY_SEPARATOR . join(DIRECTORY_SEPARATOR, $pathParts);
    }

    /**
     * checks if given path is located within root path
     */
    public function contains(string $path): bool
    {
        $realpath = realpath($path);
        if (false === $realpath) {
            return false;
        }

        return substr($realpath, 0, strlen($this->rootpath)) === $this->rootpath;
    }

    /**
     * returns list of source pathes defined for autoloader
     *
     * Relies on autoloader generated by Composer. If no such autoloader is
     * present the list of source pathes will be empty.
     *
     * @return string[]
     */
    public function sourcePathes(): array
    {
        $vendorPathes = [];
        foreach (array_merge($this->loadPsr0Pathes(), $this->loadPsr4Pathes()) as $pathes) {
            /** @var  string|string[]  $pathes */
            if (is_array($pathes)) {
                $vendorPathes = array_merge($vendorPathes, $pathes);
            } else {
                $vendorPathes[] = $pathes;
            }
        }

        return $vendorPathes;
    }

    /**
     * loads list of pathes defined via PSR-0
     *
     * @return string[]
     */
    private function loadPsr0Pathes(): array
    {
        if (file_exists($this->rootpath . '/vendor/composer/autoload_namespaces.php')) {
            return require $this->rootpath . '/vendor/composer/autoload_namespaces.php';
        }

        return [];
    }

    /**
     * loads list of pathes defined via PSR-4
     *
     * @return string[]
     */
    private function loadPsr4Pathes(): array
    {
        if (file_exists($this->rootpath . '/vendor/composer/autoload_psr4.php')) {
            return require $this->rootpath . '/vendor/composer/autoload_psr4.php';
        }

        return [];
    }

    /**
     * detects root path
     *
     * @return string
     */
    private function detectRootPath(): string
    {
        static $rootpath = null;
        if (null === $rootpath) {
            if (\Phar::running() !== '') {
                $rootpath = dirname(\Phar::running(false));
            } elseif (file_exists(__DIR__ . '/../../../../../autoload.php')) {
                // stubbles/values is inside the vendor dir of the application
                // it is a dependency of
                $rootpath = realpath(__DIR__ . '/../../../../../../');
            } else {
                // local checkout while development
                $rootpath = realpath(__DIR__ . '/../../../');
            }
        }

        return $rootpath;
    }
}
